### ISSUE TITLE
Insufficient space on your system?

### ISSUE THREAD

**Issue by rob-heine** [ohmybash/oh-my-bash#26]
Hi there,

trying to install omb in my local cygwin installation using

```
sh -c "$(wget https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh -O -)"
```

The output is 

```
Updating Oh My Bash
From https://github.com/ohmybash/oh-my-bash
 * branch            master     -> FETCH_HEAD
Already up to date.
Current branch master is up to date.
         __                          __               __
  ____  / /_     ____ ___  __  __   / /_  ____ ______/ /_
 / __ \/ __ \   / __ `__ \/ / / /  / __ \/ __ `/ ___/ __ \
/ /_/ / / / /  / / / / / / /_/ /  / /_/ / /_/ (__  ) / / /
\____/_/ /_/  /_/ /_/ /_/\__, /  /_.___/\__,_/____/_/ /_/
                        /____/
Hooray! Oh My Bash has been updated and/or is at the current version.
To keep up on the latest news and updates, follow us on GitHub: https://github.com/ohmybash/oh-my-bash
npm ERR! code ENOTSUP
npm ERR! errno 129
npm ERR! nospc npm completion supported only in MINGW / Git bash on Windows
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rob\AppData\Roaming\npm-cache\_logs\2018-08-01T06_54_21_449Z-debug.log
```

The `debug.log` mentioned above contains:

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\rob\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'completion' ]
2 info using npm@6.2.0
3 info using node@v8.5.0
4 verbose config Skipping project config: C:\Users\rob/.npmrc. (matches userconfig)
5 verbose stack Error: npm completion supported only in MINGW / Git bash on Windows
5 verbose stack     at EventEmitter.completion (C:\Users\rob\AppData\Roaming\npm\node_modules\npm\lib\completion.js:50:13)
5 verbose stack     at Object.commandCache.(anonymous function) (C:\Users\rob\AppData\Roaming\npm\node_modules\npm\lib\npm.js:159:13)
5 verbose stack     at EventEmitter.<anonymous> (C:\Users\rob\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js:126:30)
5 verbose stack     at _combinedTickCallback (internal/process/next_tick.js:131:7)
5 verbose stack     at process._tickCallback (internal/process/next_tick.js:180:9)
6 verbose cwd C:\Users\rob\.oh-my-bash
7 verbose Windows_NT 10.0.16299
8 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rob\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "completion"
9 verbose node v8.5.0
10 verbose npm  v6.2.0
11 error code ENOTSUP
12 error errno 129
13 error nospc npm completion supported only in MINGW / Git bash on Windows
14 error nospc There appears to be insufficient space on your system to finish.
14 error nospc Clear up some disk space and try again.
15 verbose exit [ 129, true ]
```

How much disk space _IS_ actually needed?

```
08:54:21 rob@lif .oh-my-bash ±|master|→ df -h
df: /v: Bad address
Filesystem               Size  Used Avail Use% Mounted on
C:/Users/rob/.cygwin  467G  323G  145G  70% /
M:                        70G   56G   15G  80% /m
O:                       2.7T  1.3T  1.5T  46% /o
P:                       110G   91G   20G  83% /p
Q:                       110G   91G   20G  83% /q
S:                       2.7T  1.3T  1.5T  46% /s
T:                        20G  1.9G   19G  10% /t
U:                        25T   24T  5.0G 100% /u
08:54:35 rob@lif .oh-my-bash ±|master|→
```

Is 145GB enough? 🤣

**Comment by momocow** [comment]
I'm also facing this problem when using OMB with Cygwin.

```
npm ERR! code ENOTSUP
npm ERR! errno 129
npm ERR! nospc npm completion supported only in MINGW / Git bash on Windows
npm ERR! nospc There appears to be insufficient space on your system to finish.
npm ERR! nospc Clear up some disk space and try again.
```

**Comment by nntoan** [comment]
@rob-heine @momocow It should not be Oh My Bash issue but the Nodejs completion issue might not fully compatiable with Cygwin.

`npm ERR! nospc npm completion supported only in MINGW / Git bash on Windows`

In order to fix this, try to disable nodejs completion under `completion` folder.
Until [this PR ready](https://github.com/ohmybash/oh-my-bash/pull/17), you guys can able to choose which completion need to be load into the system.

I'm so sorry for the delay answer.

Cheers.

**Comment by Kreyren** [comment]
In theory we could provide some logic in bash for this, but i think that this should be handled as npm issue. 

Closing unless you have valid point to re-open (suggestion to fix, logic in bash, etc..).
